[2021-10-21 18:54:16,711] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Fire_Incidents.Step_Function 2021-10-21T18:54:15.048956+00:00 [queued]>
[2021-10-21 18:54:16,726] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Fire_Incidents.Step_Function 2021-10-21T18:54:15.048956+00:00 [queued]>
[2021-10-21 18:54:16,726] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 18:54:16,726] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-10-21 18:54:16,726] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 18:54:16,733] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): Step_Function> on 2021-10-21T18:54:15.048956+00:00
[2021-10-21 18:54:16,737] {standard_task_runner.py:52} INFO - Started process 66 to run task
[2021-10-21 18:54:16,739] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fire_Incidents', 'Step_Function', '2021-10-21T18:54:15.048956+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/tutorial.py', '--cfg-path', '/tmp/tmp98yudbki', '--error-file', '/tmp/tmpyjnb1dz8']
[2021-10-21 18:54:16,740] {standard_task_runner.py:77} INFO - Job 11: Subtask Step_Function
[2021-10-21 18:54:16,771] {logging_mixin.py:104} INFO - Running <TaskInstance: Fire_Incidents.Step_Function 2021-10-21T18:54:15.048956+00:00 [running]> on host 8ad12bb33883
[2021-10-21 18:54:16,799] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Fire_Incidents
AIRFLOW_CTX_TASK_ID=Step_Function
AIRFLOW_CTX_EXECUTION_DATE=2021-10-21T18:54:15.048956+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-21T18:54:15.048956+00:00
[2021-10-21 18:54:18,077] {logging_mixin.py:104} INFO - The response is:
[2021-10-21 18:54:18,078] {logging_mixin.py:104} INFO - {'executionArn': 'arn:aws:states:us-west-2:104674085951:execution:fire-incidents-orchestrator-dev:04039f28-2acd-456f-ad27-3cb54f71dbef', 'startDate': datetime.datetime(2021, 10, 21, 18, 54, 17, 948000, tzinfo=tzlocal()), 'ResponseMetadata': {'RequestId': 'f733b55e-b8f1-49f0-8ae7-1e8a11da0bb9', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'f733b55e-b8f1-49f0-8ae7-1e8a11da0bb9', 'content-type': 'application/x-amz-json-1.0', 'content-length': '164'}, 'RetryAttempts': 0}}
[2021-10-21 18:54:18,078] {logging_mixin.py:104} INFO - The type of response is:
[2021-10-21 18:54:18,078] {logging_mixin.py:104} INFO - <class 'dict'>
[2021-10-21 18:54:18,383] {logging_mixin.py:104} INFO - The status of response is:
[2021-10-21 18:54:18,383] {logging_mixin.py:104} INFO - RUNNING
[2021-10-21 18:54:30,980] {logging_mixin.py:104} INFO - final_status is:
[2021-10-21 18:54:30,981] {logging_mixin.py:104} INFO - ABORTED
[2021-10-21 18:54:30,984] {python.py:118} INFO - Done. Returned value was: None
[2021-10-21 18:54:30,997] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=Fire_Incidents, task_id=Step_Function, execution_date=20211021T185415, start_date=20211021T185416, end_date=20211021T185430
[2021-10-21 18:54:31,023] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-21 18:54:31,044] {local_task_job.py:146} INFO - Task exited with return code 0
